### ISSUE TITLE
Problem with image converter

### ISSUE THREAD

**Issue by Polarisru** [littlevgl/utils#11]
Hello, 
I have just tried the image converter to get a logo picture with a lot of white background and was very disappointed, the generated c array was wrong. I have tried different image formats (png, bmp) from different software tools (Paint.net, XNView) but without success. As I mentioned, the picture has a lot of white background, but the generated array was full of 
0x05, 0x00, 0x05, 0x00, 0x05, 0x00, 0x05, 0x00, 0x05, 0x00, ...
I have used 16 bit color depth, so it seems more to be black. And it was also displayed as a black rectangle.
I have tried to put some 0xff, 0xff to the generated array and got the right result - white color for the corrected area.
Probably it is something wrong with the converter. I have taken a look at the source code, may be it cann't convert bitmaps with 32 bits color encoding? Just guessing.

**Comment by kisvegabor** [comment]
Hi,

Please attach an image which was not working.
