### ISSUE TITLE
LV_ATTRIBUTE_MEM_ALIGN in font converter

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/utils#18]
https://github.com/littlevgl/lv_utils/blob/bb8954ed13822c50ce6545112d1e40bdbb57fc3a/font_conv_core.php#L212

Do we need the `LV_ATTRIBUTE_MEM_ALIGN` attribute here as well?

**Comment by kisvegabor** [comment]
Good question, but I think it's not required.

Mis-aligned memories caused an issue when they were passed to a periphery (such as DMA) which expected aligned memory. The glyphs are processed byte-by-byte (or even bit-by-bit) in the library and never passed to hardware.

**Comment by embeddedt** [comment]
@kisvegabor Thanks for the clarification!
