### ISSUE TITLE
image converter throws syntax errors

### ISSUE THREAD

**Issue by 8bit-meiko** [littlevgl/utils#2]
i tried to run the image converter with both a jpg and png file from my windows terminal (command: python image_conv.py test.png 16 0 )

but got a syntax error as response(?)
```

C:\Users\Ramon\Downloads\lv_utils-master\lv_utils-master\img_conv>python img_con
v.py nice.png
  File "img_conv.py", line 14
    print "No inputfile. Usage: ", sys.argv[0], " filename [OPTIONAL color depth
 (8/16/24)]"
                                ^
SyntaxError: invalid syntax
```

this is with python 3.6 by the way.

**Comment by kisvegabor** [comment]
Hi, 
which branch do you use?

**Comment by 8bit-meiko** [comment]
I simply picked the master branch

**Comment by kisvegabor** [comment]
I sent you the new arduino lib: https://github.com/littlevgl/lvgl/issues/49

Please try img_conv .py from dev-5.0 branch, because it is compatible with the version you use

**Comment by kisvegabor** [comment]
v5.0.0 is released. and some updates happened. 
Please try the lv_utils (master)

**Comment by kisvegabor** [comment]
As the old scripts are replaced with online converters I close this issue.

Thank you for telling your experiences! :)
