### ISSUE TITLE
file bdf_font_converter.py seems too old

### ISSUE THREAD

**Issue by Changes729** [littlevgl/utils#29]
Hello,

I want to use bdf in my littlevGL program to show some small fonts on small screen.

but the file converted by bdf_font_converter.py cannot be loaded. Is there any other way to convert BDF files?

Regards!

**Comment by embeddedt** [comment]
BDF is no longer supported directly by LittlevGL. The font converter in this repository is for the old 5.3 version.

You'll need to convert your fonts to a supported font (i.e. TTF) or find a different font to use.

If you need more assistance please open an issue on the new repo (https://github.com/littlevgl/lv_font_conv) or the forum.
