### ISSUE TITLE
Can the old font converters be removed from this repository?

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/utils#32]
We've kept the old font converters in this repository for a while now. Documentation for them takes up a lot of space in the README, and it appears that most people are using 6.x now.

How about we remove them from the repository, but leave a link to the commit prior to their removal in the README?

**Comment by kisvegabor** [comment]
> We've kept the old font converters in this repository for a while now. Documentation for them takes up a lot of space in the README, and it appears that most people are using 6.x now.

I agree.

> How about we remove them from the repository, but leave a link to the commit prior to their removal in the README?

That's a great idea! It'd be only one line.

**Comment by embeddedt** [comment]
Removed in https://github.com/littlevgl/lv_utils/commit/46a04655096bfc92c0e4e3069a88b407836a40e1.

**Comment by kisvegabor** [comment]
Thank you!
