### ISSUE TITLE
the Online Image to C Array Converter has bug in converting images to binary files

### ISSUE THREAD

**Issue by armembedded** [littlevgl/utils#34]
Im going to use the Online Image to C Array Converter to convert to a jpg image to Binary RGB565.
unfortunately the converter has bug in  in converting images to binary files.

**Comment by embeddedt** [comment]
You'll need to provide more details. Please upload:

* The image were you trying to convert
* A screenshot of the settings you used with the converter

**Comment by armembedded** [comment]
I solved this issue by disabling  download manger plugin 
thank you

**Comment by kisvegabor** [comment]
> I solved this issue by disabling download manger plugin

Why was it causing problems?
