### ISSUE TITLE
a document page not found

### ISSUE THREAD

**Issue by armembedded** [littlevgl/utils#35]
following link page not found: 
https://docs.littlevgl.com/en/html/overview/overview/object#screen-the-most-basic-parent

**Comment by embeddedt** [comment]
Thanks. This is the correct link: https://docs.littlevgl.com/en/html/overview/object.html#screen-the-most-basic-parent

Where did you find this?

**Comment by armembedded** [comment]
I found it in the online document

**Comment by embeddedt** [comment]
Yes, but which page? I can't fix the broken link if I don't know where it is. :slightly_smiling_face:

**Comment by embeddedt** [comment]
As there was no response, I'll close this issue. If anyone does find a broken link, please comment with its location and I'll fix it.
